polls/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls_app.urls')),
    path('admin/', admin.site.urls),
]

polls_app/urls.py
from django.urls import path

from . import views

app_name = 'polls_app'

# urlpatterns = [
#     path("", views.index, name='index'),
#     path("<int:question_id>/", views.details, name="details"),
#     path("<int:question_id>/results/", views.results, name='results'),
#     path("<int:question_id>/votes/", views.votes, name='vote'),
# ]

urlpatterns = [
    path("", views.IndexView.as_view(), name='index'),
    path("<int:pk>/", views.DetailView.as_view(), name='details'),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/votes/", views.votes, name='vote')
]

polls_app/models.py
import datetime
from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        now = timezone.now()
        return now  - datetime.timedelta(days=1) <= self.pub_date <= now

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls_app/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.urls import reverse
from django.views import generic
from polls_app.models import Choice, Question
from django.utils import timezone
import datetime
# Create your views here.

# def index(request):
#     latest_questions = Question.objects.order_by('-pub_date')[:5]
#     # output = ', '.join([q.question_text for q in latest_questions])
#     template = loader.get_template("polls_app/index.html")
#     context = {
#         'latest_questions_list': latest_questions
#     }
#     return HttpResponse(template.render(context, request))


# def details(request, question_id):
#     try:
#         question = Question.objects.get(pk=question_id)
#     except Question.DoesNotExist:
#         raise Http404("Question does not exist")
#     return render(request, 'polls_app/details.html', {'question': question})

# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls_app/results.html', {'question': question})

def votes(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls_app/details.html', { 'question': question, 'error-message': "You did not select a choice" })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls_app:results', args=(question.id,)))

class IndexView(generic.ListView):
    template_name = "polls_app/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
    

class DetailView(generic.DetailView):
    model = Question
    template_name ="polls_app/details.html"


class ResultsView(generic.DetailView):
    model = Question
    template_name ="polls_app/results.html"

polls_app/templates/polls_app/details.html
{% block content %}
<form action="{% url 'polls_app:vote' question.id %}" method="post">
  {% csrf_token %}
  <fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %} <strong> {{ error_message }} </strong> {% endif %}
    {% for choice in question.choice_set.all %}
    <input
      type="radio"
      name="choice"
      id="choice{{ forloop.counter }}"
      value="{{choice.id }}"
    />
    <label for="choice{{ forloop.counter }}"> {{ choice.choice_text }} </label>
    <br />
    {% endfor %}
  </fieldset>
  <input type="submit" value="Vote"  class="btn" />
</form>
{% endblock %}

polls_app/templates/polls_app/index.html
{% extends 'polls_app/layout/base.html' %}

{% block content %} 
{% if latest_question_list %}

<ul>
    {% for question in latest_question_list %}
    <li> <a href="{% url 'polls_app:details' question.id %}" >{{ question.question_text }}</a></li>
    {% endfor %}
</ul>

{% else %}
<p> No polls  available</p>
{% endif %}
{% endblock content %}

polls_app/templates/polls_app/layout/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'polls_app/style.css' %}" />
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    {% block content %}

     {% endblock %}
    
</body>
</html>

polls_app/templates/polls_app/results.html
{% extends "polls_app/layout/base.html" %}
{% block content %}
<h1>{{ question.question_text }}</h1>
<ul>
  {% for choice in question.choice_set.all %}
  <li>
    {{ choice.choice_text }} - {{ choice.votes }} vote{{ choice.votes| pluralize }}
  </li>
  {% endfor %}
</ul>

<a href="{%  url 'polls_app:details' question.id %}" class="btn"> Vote again </a>
{% endblock %}